########################################################################################################################
#                                                CI WORKFLOW CONTROLLER                                                #
########################################################################################################################

name: CI Controller

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - develop
      - release/*
      - master
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  detect-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Detect Environment and Echo
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          BASE_BRANCH="${GITHUB_BASE_REF}"
          EVENT_NAME="${{ github.event_name }}"

          echo "Event: $EVENT_NAME"
          echo "Branch: $BRANCH_NAME"
          echo "Base Branch: $BASE_BRANCH"

          if [[ "$EVENT_NAME" == "push" ]]; then
            # Only feature/* branches are allowed to push
            if [[ "$BRANCH_NAME" == feature/* ]]; then
              echo "Environment: development"
            else
              echo "❌ Direct pushes to $BRANCH_NAME are not allowed."
              exit 1
            fi
          elif [[ "$EVENT_NAME" == "pull_request" ]]; then
            if [[ "$BRANCH_NAME" == feature/* && "$BASE_BRANCH" == "develop" ]]; then
              echo "Environment: staging"
            elif [[ "$BRANCH_NAME" == develop && "$BASE_BRANCH" == release/* ]]; then
              echo "Environment: release"
            elif [[ "$BRANCH_NAME" == release/* && "$BASE_BRANCH" == master ]]; then
              echo "Environment: production"
            else
              echo "Environment: unknown or invalid PR target"
              exit 1
            fi
          else
            echo "Unhandled event type: $EVENT_NAME"
            exit 1
          fi
