########################################################################################################################
#                                                CI WORKFLOW CONTROLLER                                                #
########################################################################################################################

name: CI Controller

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  detect-environment:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.setenv.outputs.env }}
    steps:
      - name: Determine Environment
        id: setenv
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

          echo "Branch: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" == "master" ]]; then
            echo "env=production" >> "$GITHUB_OUTPUT"
          elif [[ "$BRANCH_NAME" == "develop" ]]; then
            echo "env=staging" >> "$GITHUB_OUTPUT"
          elif [[ "$BRANCH_NAME" == release/* ]]; then
            echo "env=release" >> "$GITHUB_OUTPUT"
          else
            echo "env=development" >> "$GITHUB_OUTPUT"
          fi

  call-development:
    if: needs.detect-environment.outputs.env == 'development'
    needs: detect-environment
    uses: ./.github/workflows/development.yml
    with:
      environment_name: development

  call-staging:
    if: needs.detect-environment.outputs.env == 'staging'
    needs: detect-environment
    uses: ./.github/workflows/staging.yml
    with:
      environment_name: staging

  call-release:
    if: needs.detect-environment.outputs.env == 'release'
    needs: detect-environment
    uses: ./.github/workflows/release.yml
    with:
      environment_name: release

  call-production:
    if: needs.detect-environment.outputs.env == 'production'
    needs: detect-environment
    uses: ./.github/workflows/production.yml
    with:
      environment_name: production
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
