########################################################################################################################
#                                                CI WORKFLOW CONTROLLER                                                #
########################################################################################################################

name: CI Controller

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  detect-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Detect Environment and Echo
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          BASE_BRANCH="${GITHUB_BASE_REF}"

          echo "Branch: $BRANCH_NAME"
          echo "Base Branch: $BASE_BRANCH"
          echo "Event: ${{ github.event_name }}"

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            if [[ "$BRANCH_NAME" == feature/* && "$BASE_BRANCH" == "develop" ]]; then
              echo "Environment: staging"
            elif [[ "$BRANCH_NAME" == develop && "$BASE_BRANCH" == release/* ]]; then
              echo "Environment: release"
            elif [[ "$BRANCH_NAME" == release/* && "$BASE_BRANCH" == master ]]; then
              echo "Environment: production"
            else
              echo "Environment: invalid PR flow"
            fi
          else
            if [[ "$BRANCH_NAME" == feature/* ]]; then
              echo "Environment: development"
            elif [[ "$BRANCH_NAME" == "develop" || "$BRANCH_NAME" == release/* || "$BRANCH_NAME" == "master" ]]; then
              echo "❌ Direct pushes to $BRANCH_NAME are not allowed. Use a PR."
              exit 1
            else
              echo "Environment: unknown branch pattern"
            fi
          fi
